name: CD

on:
  pull_request:
    branches:
      - main
      - development
    types: closed

jobs:
  publish-docker-image:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    env:
      NODE_ENV: 'prod'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up environment variables
        env:
          ENV: ${{ github.ref == 'refs/heads/main' && secrets.ENV || secrets.ENV_DEV }}
        run: echo "${{ env.ENV }}" | base64 -d > .env
      - name: Log in to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        env:
          IMG: ${{ github.ref == 'refs/heads/main' && ':latest' || ':dev-latest' }}
        with:
          context: ./
          push: true
          tags: ${{ github.repository }}${{ env.IMG }}
      - name: Clean up
        run: rm -rf .env

  deploy:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    needs: publish-docker-image
    env:
      SSH_PRIVATE_KEY: ${{ secrets.AWS_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      WORK_DIR: ${{ secrets.WORK_DIR }}
      SLUG: ${{ github.ref == 'refs/heads/main' && '-prod' || '-dev' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get repo name
        run: |
          echo "${{github.repository}}" | cut -d "/" -f 2 > repo.txt
          echo "REPO_NAME=$(cat repo.txt)" >> $GITHUB_ENV
          rm -rf repo.txt
      - name: Set up SSH key
        run: |
          echo "${{ env.SSH_PRIVATE_KEY }}" | base64 -d > ~/aws.pem
          chmod 600 ~/aws.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ env.SSH_HOST }} > ~/.ssh/known_hosts
      - name: Deploy ${{ env.SLUG }}
        run: |
          ssh -i ~/aws.pem -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SSH_HOST }} "cd ${{ env.WORK_DIR }}/${{env.REPO_NAME}}${{env.SLUG}} && docker-compose pull && docker-compose up -d && docker image prune -f && exit"
      - name: Clean up
        run: rm -rf ~/aws.pem
