name: CI

on:
  pull_request:
    types: [closed, review_requested, ready_for_review, synchronize, opened]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-package-lock-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-package-lock-
            ${{ runner.os }}-

      - name: Cache Cypress
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-
            ${{ runner.os }}-

      - uses: actions/setup-node@v4
        with:
          node-version: 22.9.x

      - name: Install Dependencies
        run: npm i

      - name: Check Format
        run: npm run check-format

      - name: Check eslint
        run: npm run lint

      - name: Check build
        run: npm run build

      - name: Run Tests
        run: |
          npm run dev &
          npm run test
